### ISSUE TITLE
change plugin structure so `this` is the plugin object, not bot

### ISSUE THREAD

**Issue by emersonveenstra** [emersonveenstra/vbot#10]

**Comment by NinjaBanjo** [comment]
+1

**Comment by NinjaBanjo** [comment]
This looks like it's going to be a larger core change than originally though. We will need to call the plugin functions from the plugin object (the loaded object) or pass a context to the register_command function.

Is this the direction we want to take? We should respect the context of the plugin as it allows for a lot more reusable code within the plugin.

This change will require a rewrite of all plugin register_command calls, not a huge effort, but definitely a large change to bot core.

**Comment by emersonveenstra** [comment]
I think we should do this, probably not for v0.2 though. The way I've been doing it (https://github.com/emersonveenstra/vbot/blob/master/plugins/eval/index.js#L7) is to .bind(this) in the register command function, so that can be an easy workaround for now

**Comment by NinjaBanjo** [comment]
If that works for a solution, it would be a lot cleaner than what I had in mind.

I'll have a play with it and see if there is anything broken in this approach.

**Comment by NinjaBanjo** [comment]
bind(this) when calling bot.register command is a viable solution. This gives flexible approaches to registering commands. my vote is to close this without change

**Comment by emersonveenstra** [comment]
Votes for: 2; votes against: 0;

:)
