### ISSUE TITLE
Make message.command switch use toUpperCase()

### ISSUE THREAD

**Issue by NinjaBanjo** [emersonveenstra/vbot#25]
https://github.com/emersonveenstra/vbot/blob/master/vbot.js#L129 checks command against switch items. https://tools.ietf.org/html/rfc2812#section-2.3.1 RFC for protocol doesn't specificy that uppercase is require. Should use toUpperCase and possible attemp to parseInt() or check if number (will always be 3 digits.)

**Comment by emersonveenstra** [comment]
Merged in with #26
