### ISSUE TITLE
Make events for messages, joins, invites, etc

### ISSUE THREAD

**Issue by emersonveenstra** [emersonveenstra/vbot#9]
will help with memo and logging

**Comment by NinjaBanjo** [comment]
Message even added in c99e154b4c8a0af1c444ced5d8568b268c735cbf

**Comment by NinjaBanjo** [comment]
Join event added in #19 waiting for pr acception

**Comment by NinjaBanjo** [comment]
@emersonveenstra I implimented the events in the parse_message function for now, we may want to refactor this. it seemed logic for the message and join events in order to keep the context creation in one place.

thoughts?
